### ISSUE TITLE
An idea for improvement

### ISSUE THREAD

**Issue by Mpic** [teddykoker/pedalnet#1]
Awesome implementation !

I stumbled upon this from Magenta : <https://storage.googleapis.com/ddsp/index.html> (also [on GitHub](https://github.com/magenta/ddsp)) and figured maybe it could be a way to permit parameter variation without having to re-train for every parameter incrementation (gain for example)...

I just drop this here as I think it could be related, but I have no time for now to investigate further.

Thanks again for this really cool stuff !

**Comment by teddykoker** [comment]
Interesting read! Such layers could certainly be added to the model add effects, but adding a "gain" effect would certainly have a different sound than dialing up the gain on the real pedal.
